services:
  tsrp:
    container_name: tsrp
    image: ghcr.io/mtzanidakis/tsrp
    restart: always
    user: 1000:1000
    environment:
      - BACKEND=http://backend
      - HOSTNAME=${HOSTNAME}
      - TS_AUTHKEY=${TS_AUTHKEY}
    volumes:
      - ./state:/var/lib/tsrp

  backend:
    container_name: backend
    image: nginx:alpine
    restart: always
