[tools]
go = "1.26.4"
golangci-lint = "2.12.2"

[env]
_.file = ".env"

[tasks.lint]
description = "Run golangci-lint"
run = "golangci-lint run"

[tasks.test]
description = "Run go tests"
run = "go test -v ./..."
